### PR TITLE
Add LICENSE

### PR DESCRIPTION
**Pull request by khronokernel**

### CODE REVIEW

**Comment by richb-hanover** [comment]
Why the choice of a Non-commercial version of the Creative Commons license? 

What are your concerns that make it important to insist on non-commercial uses? 

I'll note that OpenWrt wiki adopted the Attribution-ShareAlike version and their community is small, though thriving. (See the bottom of https://openwrt.org/ )Thanks.

**Comment by khronokernel** [comment]
> But I would like to know why a non-commercial license was selected...

@richb-hanover Main reason we chose non-commercial was due to issues we've had in the past of people reposting our work behind a paywall(ie. technolli with his $1 paywall for open sourced files, Morgonaut with her patreon). 

All of our work is free and we don't personally approve of users taking others work and charging for it, so if we can have a bit of leverage for more atrocious situation(ie. Tonymacx86 reposting the entire guide on their site) we can at least take it down easily. Obviously if Tonymacx86 removed ads from the site entirely(as just removing from just the guide could still count, as the guide would be used as a "selling point" for users to come to tonymacx86), it would be a bit more difficult to really pursue action as it would then could be under non-profit/educational.

**Comment by richb-hanover** [comment]
My question to (all of) you: What is your goal? You haven't said, but I suspect you want to make _The Best Hackintosh Guide on the Planet (tm)_. And I also am guessing that you all would like to gain the cred that properly should flow to the authors/creators of the guide.

Is this close to right? Thanks.

**Comment by dhinakg** [comment]
Our goal is pretty much to have a proper, updated, **good** guide for hackintoshing, as we haven't seen any that match these criteria. Cred is important, but not by a lot. Our main issue (which has happened before) is that people rehost the guide under their name and shove a small credit to us for the whole guide. It's fine if you actually change something (ie. add Sandy Bridge) and maintain a fork of it (although the chance we wouldn't want to merge and support it is rare) but making no actual content changes and claiming it as your own is something we don't like.

We also don't want YouTubers (mainly the likes of Morgonaut and Technolli) profiting off of a guide which was written entirely on a volunteer basis. It would be fine if they credited and linked to the guide for more info (especially because a YouTube tutorial  and actually explained it properly but they butcher it and also sell things (EFIs) created off of our work. An example of a good video was Snazzy Labs, as they contacted Mykola (this was before the move to dortania) and actually talked with them to make the video, and it's one of the few (mainly only) videos we recommend if you're a visual learner.

**Comment by richb-hanover** [comment]
These thoughts are helpful. I'm new to this project, so I don't have any say in this. But I have been writing software professionally for four decades, and have watched a lot of projects grow (and fade). I will offer a few thoughts:

> Our goal is pretty much to have a proper, updated, **good** guide for hackintoshing, as we haven't seen any that match these criteria. 

I agree - a good guide to Hackintosh is sorely missing.

> Cred is important, but not by a lot.

I get it. It's also interesting that you haven't mentioned any kind of financial benefit. That's fine: it's good to be clear about it.

Finally, I'll bet that you also would like the world to know about the Guides, and read and use them. 

> Our main issue (which has happened before) is that people rehost the guide under their name and shove a small credit to us ... and claiming it as your own is something we don't like.

I can totally understand that. And you're already doing something about it: adding a license. It'll clearly state a) that it's your work (not anyone else's), and b) the terms under which people can use it. 

> We also don't want YouTubers (mainly the likes of Morgonaut and Technolli) profiting off of a guide which was written entirely on a volunteer basis. 

And here's where I'm going to offer three bits of advice from my years of watching open-source projects.

1. "Generous" projects prosper. They encourage others to use their work, attract new people to help make it even better, and because it's good work, more people use it. On the other hand, "stingy" projects (for lack of a better word) discourage people. They wind up closing themselves off, spending time making sure that people don't "take advantage of them". They waste energy on worrying, not improving the project. 

   I think you're at risk of falling into the "stingy" realm.
  
2. I think you're misplacing your worries. I could understand how you would be alarmed if Microsoft or Apple wanted to horn in on this work. But that's not going to happen. Even if their YouTube receipts covers their rent, they're not "getting rich".

   Nonetheless, they are providing a service that doesn't exist. There's no good written guide (but there will be soon :-) They're providing instructions, which satisfies an apparent need. Although they are bundling things that anyone could obtain, that's common in the real world. After all, you're happy to pay a premium to buy a loaf of bread, instead of making your own from ingredients that would cost far less. 

3. You wrote:
   > It would be fine if they credited and linked to the guide for more info (especially because a YouTube tutorial and actually explained it properly but they butcher it and also sell things (EFIs) created off of our work. An example of a good video was Snazzy Labs, as they contacted Mykola (this was before the move to dortania) and actually talked with them to make the video, and it's one of the few (mainly only) videos we recommend if you're a visual learner.

   I don't know your history with these people. One (Snazzy Labs) seemed quite reasonable to work with. Maybe there were harsh words sometime in the past - perhaps things can be healed.

I encourage you to consider what it would mean to invite them in. Ask them how to make the Guides better, then incorporate those changes. Offer to help them give better advice in their videos. In return, ask them to mention the Guides - with proper attribution. 

I don't think a prohibition on commercial use serves you well. Between those three Youtubers, there are well over a million views. If they find the Guides to be useful, they will mention them. If nothing else, you'll get the attribution you desire, plus the psychic reward of knowing your good work is being used.

All that said, as a newcomer I fully support whatever choice you make. Thanks for listening.

**Comment by richb-hanover** [comment]
I hope that I have not thrown a permanent wrench into this discussion. 

As I said initially, I am a newcomer to this project. I have offered my thoughts on the kind of license, but don't expect that I would have any say in making decisions. Thank you again for listening.

**Comment by dhinakg** [comment]
I've been very busy lately, and the same goes for the other team members. Hopefully we can finalize our decision on this sometime next week.

**Comment by richb-hanover** [comment]
Great!

**Comment by Download-Fritz** [comment]
@richb-hanover I'm not part of this team, but I semi-encouraged them to form one in the first place, and as an OpenCore maintainer (speaking for myself and **only** myself here), here's my deal with this:
Yes, it should be easy to contribute and move such a project forward. Yes, it is nice if other people can take actual advantage of the project. Yes, I think even commercial influence is fine so long as it is a clear benefit. Does any of this happen however? No, it does not. Quite the opposite, and here's why:
1) People are lusty for not only credit but also money.
2) People think to know stuff when they don't.
3) People seem to be fine sharing mediocre to terrible advice because "it may work" or "we're unpaid volunteers".
4) People seem to be fine releasing stuff that clearly does not age well (e.g. cursed workarounds like AptioFix-20000) without any such note and then just abandon whatever they shared.

There probably are many more examples, but you get the point. Especially from a commercial direction, nothing valuable is ever to come out of it, because it simply is not interesting for people with technical competence (you'd get dizzy if you knew what one would have to pay for the developments by Acidanthera, let alone the rest of the community) and very interesting for people catching noobs, as it's an easy buck. While of course many people or communities may opt to exclude commercial usage due to ego or being hurt over other people monetarily profiting (here assuming in good faith the fee is actually justified, e.g. labour time), this just provides an easy way to shut down mediocre garbage people are lured into paying for (they can get better for free just fine).

Taking OpenCore as an example for allowing commercial usage, most people trying to take commercial advantage are stupid and will just hurt themselves (e.g. opencore.computer as you may have heard, violating not only our but also Apple's copyright) - legitimate commercial advantage with this specific software is not too easily achievable, neither beneficial (how even?) nor maliciously (probably sue'd by Apple at some point). As for parts of the code, we are more than happy if we can help e.g. firmware vendors with more secure code, we all profit from that anyway. I would definitely prefer for companies to use our code than individuals that provide mediocre spinoffs that only break our software design.

Speaking about this project/community specifically, the goal was to have content with some quality control - instead of random people who release unverified text walls somewhere, the idea is there is a centralised community that cross-checks content and ensures it is good practice. For that, we are in contact with the team frequently to resolve deeper technical misconceptions within the texts, which are then fixed very quickly. Looking at how with individual posters this process is very unreliable and slow (you first have to get into contact, somehow explain the issue to someone you don't know or know what their technical competence is, the poster might have quit or is taking a break, etc), I personally believe this is superiour to similar offerings and should be preserved as such by preventing fragmentation and spreading of dated content as well as bad advice.

Does this sound super arrogant in an "we have the best and have to silence the competition" manner? Yes, it somewhat does. Is it wrong? I don't think so, I think we should focus on how to provide the best user experience here rather than worrying about the unlikely case of good external work being limited by certain decisions - everyone is free to join if they want to improve this content, or just make their own if they have different beliefs. Many people may attend the "everything is subjective and to each their own" attitude, if you however look at the time and effort spent on OpenCore, its documentation and community materials, I hope you understand we're pretty convinced of our (design) philosophies and advice, and to ensure a high level of quality, we need to be.

**Comment by richb-hanover** [comment]
@Download-Fritz I really appreciate your thoughtful response. You don't need to convince me: as I said earlier, I accept whatever the group decides regarding the license. But there's real value in discussing the underlying principles for your decision. That has happened - good work.

I know you're concerned by dilettantes who create a little content, and then walk away from it. However, I gained a lot of value from some of the Youtubers who were cited, since OpenCore currently lacks good introductory information. But I'm a deeply technical guy, was seeking a broad overview of the process, and could filter out the stuff that "didn't sound right."

I agree with your goal: To make definitive documentation that's both correct and approachable by newcomers to the project. That's why I created PR #29 to address some of the questions that I had when I came to the project. I'm hopeful that it can be (edited and) merged.

Best regards, Rich

**Comment by Download-Fritz** [comment]
@richb-hanover "However, I gained a lot of value from some of the Youtubers who were cited, since OpenCore currently lacks good introductory information."
That is exactly what all this is about. OpenCore will unlikely get any first-party introduction or guides that suit the masses, we do not have the resources for that. But apparently Dortania does, so we support them with information and review, and so far we're quite happy with the results.

Usually those video tutorials are based on these kind of written guides, so I can't imagine anything but the most basic stuff missing from the guides here. Your changes in the PR definitely make some things easier to read (especially the endless "Make sure that..." compilations), but I don't think I have the time to check all details. Either way, thanks for contributing!

As you say you're a technical guy, we generally do not mind PRs at Acidanthera either. :)

**Comment by dhinakg** [comment]
Does anyone have any objections?

**Comment by dhinakg** [comment]
bruh

**Pull request merged**
